import random

def fake_subject():
    return random.choice(subjects)


subjects = [
    "Mathematics",
    "Physics",
    "Chemistry",
    "Biology",
    "Computer Science",
    "Engineering",
    "Literature",
    "History",
    "Philosophy",
    "Political Science",
    "Psychology",
    "Sociology",
    "Anthropology",
    "Economics",
    "Business Administration",
    "Marketing",
    "Accounting",
    "Law",
    "Medicine",
    "Nursing",
    "Pharmacy",
    "Architecture",
    "Art History",
    "Music Theory",
    "Theatre Studies",
    "Environmental Science",
    "Geology",
    "Geography",
    "Astronomy",
    "Linguistics",
    "Spanish",
    "German",
    "Chinese",
    "Ukrainian",
    "Education",
    "Communication Studies",
    "Journalism",
    "Film Studies",
    "Cultural Studies",
    "Gender Studies",
    "Religious Studies",
    "Physical Education",
    "Agricultural Sciences",
    "Veterinary Medicine"
]

def fake_group_name():
    return random.choice(group_list)

group_list = [
    "Mathematics 101A",
    "Physics 101B",
    "Chemistry 102A",
    "Biology 102B",
    "Computer Science 103A",
    "Engineering 103B",
    "Literature 104A",
    "History 104B",
    "Philosophy 105A",
    "Political Science 105B",
    "Psychology 106A",
    "Sociology 106B",
    "Anthropology 107A",
    "Economics 107B",
    "Business Administration 108A",
    "Marketing 108B",
    "Accounting 109A",
    "Finance 109B",
    "Law 110A",
    "Medicine 110B",
    "Nursing 111A",
    "Pharmacy 111B",
    "Architecture 112A",
    "Art History 112B",
    "Music Theory 113A",
    "Theatre Studies 113B",
    "Environmental Science 114A",
    "Geology 114B",
    "Geography 115A",
    "Astronomy 115B",
    "Latyn 116A",
    "Spanish 116B",
    "German 117A",
    "Chinese 117B",
    "Ukrainian 118A",
    "Education 118B",
    "Communication Studies 119A",
    "Journalism 119B",
    "Film Studies 120A",
    "Cultural Studies 120B",
    "Gender Studies 121A",
    "Religious Studies 121B",
    "Physical Education 122A",
    "Agricultural Sciences 122B",
    "Veterinary Medicine 123A"
]